### ISSUE TITLE
Category Sidebar messed up

### ISSUE THREAD

**Issue by coolbung** [joomla-extensions/install-from-web-server#9]
NOTE: I'm creating this issue so that someone who wants to wrap up this only remaining piece for the JED3 integration can easily know what is needed and get up to speed faster.

The category sidebar currently displays a flat list of categories, instead of the parent-child that was before. 

On a broad level this is what needs to happen
1. The home page of the Web Installer needs to show only the top level categories in the sidebar
2. When the user clicks on one of the categories in the sidebar, the right section will show the extensions from that category 
3. In this case, only that particular category should get expanded in the sidebar and show the children from this category

The code that generates this is included in the following files - 
- components/com_apps/models/base.php in the getCategories() method. It is recommended to rewrite this function.
- layouts/joomla/apps/category_sidebar.php
- layouts/joomla/apps/category_sidebar_ul.php

**Comment by andergmartins** [comment]
I was trying to test it and check if I can help with that, but I'm not able to run the server locally yet.

@coolbung I have tried your fork, following the steps here: https://github.com/joomla-extensions/install-from-web-server/pull/4#issuecomment-75331768

I see this error when I try to use the web installer: 

    1146 Table 'web-installer-server.jos_mt_cats' doesn't exist SQL=SELECT cat_id AS id,cat_name AS name,alias,cat_desc AS description,cat_parent AS parent FROM jos_mt_cats WHERE cat_published = 1 AND cat_approved = 1 ORDER BY cat_parent, cat_name ASC

In the 4) I have used my local database, pointing to the install-from-web-server's local db.
Btw, com_apps is using a hardcoded db prefix (maybe because those are legacy tables for the old JED?). If that is the case, from where can I get the #__mt_cats table and dependencies?

**Comment by stevejburge** [comment]
Hey guys. Is this vital to ensure that Install from Web is active when Joomla 3.4 arrives?

If so, we're happy to set aside some dev time to help make it happen.

**Comment by wilsonge** [comment]
All this work is on the server side so whilst it's nice it's not essential - and the install from web is 'core supported' which means it can be updated standalone from Joomla anyhow.

**Comment by vdrover** [comment]
Same here. What can we do? Would be a shame to have a major release ship with a blemish.

**Comment by wilsonge** [comment]
Vic i sent an email to you with the details of the API (you admin account at anything digital - sorry only one i had on my list and trying to focus on 3.4 atm). The actual details of the issue are listed by ashwin in detail here

**Comment by vdrover** [comment]
victor.drover@osm works :)

**Comment by nicksavov** [comment]
@andergmartins' issue with `Table 'web-installer-server.jos_mt_cats' doesn't exist` was resolved by making sure to use the newjed branch. The master branch has the old JED server code.

@vdrover let us know if you need any help with the setup.

**Comment by vdrover** [comment]
A little more details on how to proceed and get our devs going would be helpful. We've received the email from George, but not sure exactly how to instruct our team to proceed.

**Comment by nicksavov** [comment]
Please give the directions at https://github.com/joomla-extensions/install-from-web-server/pull/4#issuecomment-75331768 a try.

For step 1, afterward make sure you're on the newjed branch of the repo, otherwise you'll run into all sorts of issues.

For step 5, the file is at plugins/installer/webinstaller/webinstaller.php

-----

Once you're set up, look at the categories on the left hand side. Notice that they are all appearing and it's a long list? That's the issue. All the categories are showing by default, rather than being nested.

The goal is to create them as nested categories. That code that needs to be modified is highlighted by Ashwin at the top of this github issue (i.e. https://github.com/joomla-extensions/install-from-web-server/issues/9#issue-58729366)

**Comment by andergmartins** [comment]
Hey guys, I may be wrong, but the JED API seems to be returning an odd data set.

Calling http://extensions.joomla.org/index.php?option=com_jed&view=category&layout=list&format=json&order=level&limit=-1 you can verify that all items have parent_id as `"parent_id":{"value":"1","text":"ROOT"}` or `"parent_id":{"value":null,"text":null}`. That makes impossible to create a nested list.

**Comment by andergmartins** [comment]
Hey guys, I may be wrong, but the JED API seems to be returning an odd data set.

Calling http://extensions.joomla.org/index.php?option=com_jed&view=category&layout=list&format=json&order=level&limit=-1 you can verify that all items have parent_id as `"parent_id":{"value":"1","text":"ROOT"}` or `"parent_id":{"value":null,"text":null}`. That makes impossible to create a nested list.

**Comment by coolbung** [comment]
Indeed! Good catch @andergmartins 
I can write to the JED developer and ask them for a fix.

The other option is that you can get only the top level categories first, then loop and get the subcategories for each parent. The API supports a filter[parent_id] parameter which will help you achieve this.

Eg: http://extensions.joomla.org/index.php?option=com_jed&view=category&layout=list&format=json&order=level&limit=-1&filter%5Bparent_id%5D=19 will give you all the subcats of the 'Communication' Category.

**Comment by andergmartins** [comment]
@coolbung thanks! About your idea, I liked! It may work for the tests until we get a definitive fix from JED. We can optimize later, after the fix.

Btw, I will use only 2 requests for now. One for the parent items and another for the selected category, since the other subcategories should be hidden anyway. That may work for the test purpose.

**Comment by wilsonge** [comment]
on that basis it might be better to start getting the level 1 items by using http://extensions.joomla.org/index.php?option=com_jed&view=category&layout=list&format=json&order=level&limit=-1&filter%5Blevel%5D=1 (i.e. filtering by level 1 items)

**Comment by andergmartins** [comment]
Hi @wilsonge, right, thanks. It is a lot better now. Just need to fix the breadcrumbs and a details with subcategories.

**Comment by coolbung** [comment]
Since we're only fetching subcats for a single category at a time, and passing that via JCache, I think that's a good production solution as well, till the JED category API issue gets fixed.

**Comment by andergmartins** [comment]
Guys, the issue I have now selecting a subcategory seems to be unfixable without the API fix. Check what I have now:
![extension manager - install 2015-02-25 10-29-20](https://cloud.githubusercontent.com/assets/407131/6371338/797fd852-bcd9-11e4-832e-c267efc4727b.png)
You can see the parent categories looks better now. Clicking in any category (A), it loads only the subcategories, ok. But if I click on a subcategory (B) we have a problem with the multiple requests.

The scenery for clicking A is: I'm able to make an initial request to grab only parent categories. So I check if any catid is selected and grab its children using the filter param for parent_id, it works. 

The scenery for clicking B is: Initial request to grab only parent categories. Now we have the catid from a subcategory. But I need the subcategories of its parent, not its own children. So I need to make a new request to discover who is the parent_id, but again, we are stuck in the JED issue, since the parent_id comes = null, for any level > 1.

The "unique" workaround I have found, is to make a request for each parent_id, to find all respective children, but that is impracticable for good performance or security. We would be multiplying the server effort by 30, for each client request.

Btw, I'm assuming we have only two levels of categories.

**Comment by andergmartins** [comment]
You can check the issue here: http://extensions.joomla.org/index.php?option=com_jed&view=category&layout=list&format=json&order=level&limit=-1&filter%5Bid%5D=43

**Comment by wilsonge** [comment]
This makes sense. @beat are you able to drop an email to JED describing this. If so please copy me in so I can push it from the leadership point of view!

**Comment by andergmartins** [comment]
Just an update. The JED team did a great job fixing the API issue quickly. It is working now:

http://extensions.joomla.org/index.php?option=com_jed&view=category&layout=list&format=json&order=level&limit=-1&filter%5Bid%5D=43

Finishing the fix and will be able to commit for tests

**Comment by beat** [comment]
@andergmartins Awesome! Thanks a lot for your help here, really highly appreciated!

**Comment by vdrover** [comment]
promising news. TY!

**Comment by andergmartins** [comment]
Just found 2 categories with level = 2 but without a parent (null):

80: Design Tools
211: Extensions Specific Non-sorted

So I have setted a conditional to ignore items with level > 1 but without a parent. Otherwise we will have php warnings.

**Comment by andergmartins** [comment]
Btw, the JED team can fix that easily in the admin, I suppose.

**Comment by wilsonge** [comment]
I guess we're done on this. Thanks to all who volunteered their time here. It's really appreciated :)
